# Generated by Django 5.0 on 2023-12-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
