# Generated by Django 5.0 on 2023-12-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_phone_record_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.BooleanField(default=False)),
                ('organization_name', models.CharField(max_length=100)),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='community_engagement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=3),
            preserve_default=False,
        ),
    ]
