# Generated by Django 5.0 on 2023-12-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_communityengagement_record_community_engagement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityengagement',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='community_engagement',
        ),
        migrations.AddField(
            model_name='communityengagement',
            name='engagement_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityengagement',
            name='student',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='webapp.record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=3),
        ),
    ]
