# Generated by Django 5.0 on 2023-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_communityengagement_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityengagement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
