# Generated by Django 5.0 on 2023-12-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_communityengagement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityengagement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id2', to='webapp.record'),
        ),
    ]
