# Generated by Django 5.0 on 2023-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_communityengagement_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityengagement',
            name='engagement_id',
        ),
        migrations.AddField(
            model_name='record',
            name='ethnicity',
            field=models.CharField(default='preferred not to say', max_length=100),
            preserve_default=False,
        ),
    ]
